name: 'MongoDB in GitHub Actions'
description: 'Start a MongoDB server (on default port 27017)'

branding:
  icon: 'database'
  color: 'green'

inputs:
  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb-version }}
    - ${{ inputs.mongodb-replica-set }}
