name: "MongoDB in GitHub Actions"
description: "Start a MongoDB server (on default port 27017)"

branding:
  icon: "database"
  color: "green"

inputs:
  mongodb-version:
    description: "MongoDB version to use"
    required: false
    default: "latest"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.mongodb-version }}
