name: Custom Port Tests

on: [push]

jobs:
  mongodb-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-port: [12345]
        mongodb-version: [4.0, 4.2, 4.4]
        node-version: [12, 14, 16]

    name: Start MongoDB Server v${{ matrix.mongodb-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: ${{ matrix.mongodb-port }}
          mongodb-replica-set: mongodb-test-rs

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/custom-port.js
        env:
          CI: true
