name: Replica Set Tests

on: [push]

jobs:
  mongodb-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2]

    name: Start MongoDB Server v${{ matrix.mongodb-version }}
    steps:
      - name: Edit /etc/hosts
        run: |
          echo "127.0.0.1 mongodb" | sudo tee -a /etc/hosts > /dev/null

      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs

      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
        env:
          CI: true

      - run: npm test ./test/replica-set.js
        env:
          CI: true
